### ISSUE TITLE
Year not storing correctly

### ISSUE THREAD

**Issue by konopisky** [sqfmi/Watchy#110]
When I'm setting the date, the year gets stored being off by -30 years. So e.g. I set the year to 2021 and it's displayed as 1991 on the watch face. I tried multiple watch faces and it's bad on all of them so it must be an RTC issue or something. 

When I set the year to 2051 it shows as 2021 on the watch face but the weekday is still off. It shows Wednesday but it should show Monday (29th November 2021)

**Comment by sqfmi** [comment]
Please update to v1.2.10 and report back if issue still persists.

**Comment by konopisky** [comment]
issue fixed! thanks 👍
