### ISSUE TITLE
Arduino String != NULL causes RTC.config() to always reset time.

### ISSUE THREAD

**Issue by GuruSR** [sqfmi/Watchy#111]
Change WatchyRTC.cpp, both _DSConfig(datetime) and _PCFConfig(datetime), the if statement for (datetime != NULL) will always succeed because datetime isn't a pointer and to a string compare, NULL winds up being "0".

The expression should be (datetime != "") and not (datetime != NULL).

**Comment by sqfmi** [comment]
Changed to != "" for better readability. However, if time is always resetting then it could be another bug that should be opened.
