### ISSUE TITLE
WatchyRTC.temperature() returns 25, should be 255.

### ISSUE THREAD

**Issue by GuruSR** [sqfmi/Watchy#112]
Looks like a typo, but the PCF8563 will return 25 degrees when it looks like it was meant to return 255 (typo).  Could this be adjusted so that if anyone reads the temperature and gets 255, they can assume it is an "error" and ignore it by using the last known good temperature they had.

**Comment by sqfmi** [comment]
Updated to 255 to reflect error state. Watchfaces should use ```currentWeather.temperature``` for temperature readings
