### ISSUE TITLE
Watch not updating if in menu for over a minute (Solution inside)

### ISSUE THREAD

**Issue by GuruSR** [sqfmi/Watchy#115]
If the code is in a menu for a duration longer than a minute, the new PCF8563 RTC will miss the minute set in the Init until the next hour.

Solution:

remove RTC.clearAlarm() in Watchy.cpp under case ESP_SLEEP_WAKEUP_EXT0: //RTC Alarm and place it inside of deepSleep().  Then authors will need to monitor the millis() (and seconds from the RTC * 1000) from the start of the init and ensure that if it is over 60,000, to update their watch face [showWatchFace()] before continuing to deepSleep().  Once the RTC.clearAlarm() is in deepSleep(), minute updates won't be missed.

**Comment by sqfmi** [comment]
Thanks @GuruSR! Fixed in v1.2.12
