### ISSUE TITLE
More Questions about Watchy

### ISSUE THREAD

**Issue by gsaker** [sqfmi/Watchy#12]
I have a few questions about the Watchy before I buy it:
- How good is the firmware, can I for example track my steps / get notifications from my phone?
- How long is the real world battery life?
- Will the firmware get better over time?
- Are there any good case designs
Thank You

**Comment by sqfmi** [comment]
For purchasing questions, please direct them to our Tindie page https://www.tindie.com/products/sqfmi/watchy/

Please only open create GitHub issues for firmware bugs or feature requests, thanks!
