### ISSUE TITLE
When wifi setup fails it writes over previous text

### ISSUE THREAD

**Issue by gudnithor** [sqfmi/Watchy#129]
When providing WifiManager with wrong credentials the error text is written on top of the "Connect to SSID: Watchy AP" text.
![photo_2021-12-26_19-55-38](https://user-images.githubusercontent.com/1818610/147419102-d3cb497e-beb8-437b-bcce-51d009cc4b96.jpg)

**Comment by sqfmi** [comment]
Thanks for the fix! Merged.
