### ISSUE TITLE
Can watchy be reset by holding buttons?

### ISSUE THREAD

**Issue by rldleblanc** [sqfmi/Watchy#134]
Sometimes the watch locks up and I have to take it apart to reset the power on it. Is there some shortcut I'm missing to reset it like a phone where you hold down one or more buttons for some number of seconds? If not is it possible to send a reset to the Arduino? I'm really new to Arduino so some push in the right direction I may be able to contribute to the project.

**Comment by sqfmi** [comment]
The only method of resetting in the current revision is to remove power (usb or battery).

**Comment by rldleblanc** [comment]
So even though the Ardunio IDE can reset the watch automatically, there is no way to listen for a long button press and do the same thing?

**Comment by sqfmi** [comment]
That is correct. You can do a soft reset using ```ESP.restart()``` but won't work if the code locks up.
