### ISSUE TITLE
DST setting not used in NTP sync

### ISSUE THREAD

**Issue by shtrom** [sqfmi/Watchy#154]
We just shifted back to Australian Eastern Standard Time (AEST), but the Watchy didn't. I realised I had it hardcoded to UTC+11 (AEDT) in the settings before, while it should have been UTC+10, with an extra hour for DST.

Reading through the code,

https://github.com/sqfmi/Watchy/blob/3c9afbb6d276d6ec0b78507f71492c35be472d07/src/Watchy.cpp#L941-L956

I see the `dst` parameter is not in use.

**Comment by shtrom** [comment]
Well, I just reset it back to UTC+1100, and found this old issue 🤣

**Comment by sqfmi** [comment]
Removed DST param and added NTP sync to use timezone from weather call
