### ISSUE TITLE
Continuous resetting of the watch

### ISSUE THREAD

**Issue by mko-mko** [sqfmi/Watchy#186]
Hi!
If I upload a watch face code (any of the example watch faces), the code successfully uploads, and I can see the new watch face on the watch, but then the watch starts resetting continuously.
Even when I unplug the watch from the PC, it contiuously reboots itself, becoming unusable.
Anyone have an idea of the cause of the problem?
Thank you very much!!!!!!

Here is the bottom part of the code I get:
```
Writing at 0x001d2885... (100 %)
Wrote 1865120 bytes (1143957 compressed) at 0x00010000 in 17.7 seconds (effective 842.3 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
```

**Comment by sqfmi** [comment]
Try updating to the latest version of the library (v1.4.2), this is probably related to #179
