### ISSUE TITLE
Face with two pages

### ISSUE THREAD

**Issue by denics** [sqfmi/Watchy#213]
dear all,
I just unpacked my watchy and I really like it. I have been playing around with faces, like many of us I think, but there is a thing I do not understand. If we use, for example, the nice, new, Mario face, how can we access the other extra information like battery, weather etc etc? is there the possibility to access another page with all the information? or modify the menu to have "all info"?

**Comment by b-bayport** [comment]
Multiple faces are possible and have been done by others. Check out this implementation: https://github.com/BraininaBowl/Brainwork-for-Watchy
