### ISSUE TITLE
Hidden warning indicates incomplete patch

### ISSUE THREAD

**Issue by wjgeorge** [sqfmi/Watchy#218]
apparently DST indicator was removed from WatchySettings and changed to use weather. The following warning indicates that the patch was not complete

In file included from /Users/xxx/Documents/Arduino/7_SEG/7_SEG.ino:2:
/Users/xxxDocuments/Arduino/7_SEG/settings.h:25:1: warning: missing initializer for member 'watchySettings::dstOffset' [-Wmissing-field-initializers]
 };

**Comment by sqfmi** [comment]
Thanks, updated in [2b327c6](https://github.com/sqfmi/Watchy/commit/2b327c64b874b32e5640a4941c96febf7e3ea03a)
