### ISSUE TITLE
Add Mac and IP address to "About Watchy"

### ISSUE THREAD

**Issue by wjgeorge** [sqfmi/Watchy#222]
see #89 where it was added to the wifi manager

**Comment by sqfmi** [comment]
Updated in ffc7de15b8b9d4732cea53520c5ec99c616b31ee

**Comment by wjgeorge** [comment]
@sqfmi always seems to show 0.0.0.0 as my IP address

**Comment by sqfmi** [comment]
Updated in 1.4.9
