### ISSUE TITLE
[7_SEG] when no wifi connection available wrong icon

### ISSUE THREAD

**Issue by denics** [sqfmi/Watchy#229]
When there is no wifi, the Face keeps displaying the last known icon which is misleading. instead I did a nice cpu bin to be displayed if weather information are not available. this also prevent to lose cycles trying to connect if the wifi is not configured.

**Comment by wjgeorge** [comment]
last known icon for what feature? Weather?

**Comment by denics** [comment]
my bad, I saw that in last version it displays nothing. however, the small little CPU is nicer :D

**Comment by sqfmi** [comment]
@denics merged in latest release, thank you!
