### ISSUE TITLE
The OTA is not working.

### ISSUE THREAD

**Issue by ewecan** [sqfmi/Watchy#234]
Hello! Why does it show BLE disconnected after I used OTA download, but firmware is not updated. The website used is https://watchy.sqfmi.com/watchfaces/

**Comment by ewecan** [comment]
Serial port prompt information：lld_pdu_get_tx_flush_nb HCI packet count mismatch (1, 2)

**Comment by sqfmi** [comment]
BLE OTA is not functional at the moment, the functionality will be updated to use web usb

**Comment by msees** [comment]
Is the BLE OTA Problem Fixed i have still the problem with the Bluetooth connection.

**Comment by escopecz** [comment]
Is there any doc for the "Update Firmware" menu option that suggests using bluetooth?
