### ISSUE TITLE
battery won't charge

### ISSUE THREAD

**Issue by rob-dodson** [sqfmi/Watchy#240]
When I plug watchy into a USB cable, the light diode comes on (red) for about 60 seconds then goes out. Not matter how long I leave the watchy connected the battery never charges.

**Comment by rob-dodson** [comment]
Actually, the light is still red, but now very dim.

**Comment by rob-dodson** [comment]
Also, the watch did work for a while when I got it, when seems to indicate the battery itself is ok.

**Comment by sqfmi** [comment]
Check to make sure the firmware is flash to the right Watchy version. If the charging light is dim, that would indicate the charging is complete.
