### ISSUE TITLE
Watchy hour keeps resetting

### ISSUE THREAD

**Issue by ckirtley** [sqfmi/Watchy#244]
I just bought a Watchy, and noticed the time keeps resetting to "21" (minutes are not affected). I have change the face through Arduino IDE but it was happening before that with the default face. If I correct it, it stays good for a few hours then flips back to 21.

**Comment by ckirtley** [comment]
> I just bought a Watchy, and noticed the time keeps resetting to "21" (minutes are not affected). I have change the face through Arduino IDE but it was happening before that with the default face. If I correct it, it stays good for a few hours then flips back to 21.

**Comment by ckirtley** [comment]
I just realised the city is set as NYC and time is overwritten by the weather function!

**Comment by sqfmi** [comment]
Yes, the timezone is overwritten by the weather API currently, will look into making it optional in the future. Apologies for the confusion!
