### ISSUE TITLE
GUILite / LVGL

### ISSUE THREAD

**Issue by niutech** [sqfmi/Watchy#25]
Is it possible to use [GuiLite](https://github.com/idea4good/GuiLite), [uGFX](https://ugfx.io/) or [LVGL](https://github.com/lvgl/lvgl) to make more advanced GUI than Adafruit GFX library? If yes, how to do it?

At least LVGL has a lot of widgets, [supports ESP32](https://blog.lvgl.io/2019-01-31/esp32) and [looks great](https://maldus512.medium.com/porting-littlevgl-for-a-monochrome-display-6c7be58851ce) on a monochrome screen.

**Comment by sqfmi** [comment]
Yes, you can definitely use those libraries as they are supported by the ESP32. You may need to find the right display driver, and also keep in mind e-ink screens don't have the same refresh rate as LCD screens, so the widget animations and callbacks will need to be adjusted as such.

**Comment by niutech** [comment]
Thanks, but where can I find the e-paper driver for LVGL? [Here](https://github.com/lvgl/lv_drivers) I cannot find one.

**Comment by sqfmi** [comment]
You can find the driver we use here: https://github.com/ZinggJM/GxEPD2/blob/master/src/epd/GxEPD2_154_D67.cpp

You will have to port it over as described here https://docs.lvgl.io/v7/en/html/porting/display.html

**Comment by niutech** [comment]
Thank you!
