### ISSUE TITLE
OpenWeather API called too frequently

### ISSUE THREAD

**Issue by bendablegears** [sqfmi/Watchy#36]
According to OpenWeather's [API care reccomendations](https://openweathermap.org/appid) it is of no benefit to call the API more often than once every 10 minutes. The current example in Watchy7SEG fetches weather data every minute.

Caching the weatherData will save battery life (due to not needing to power up the wifi radio) and allow Watchy to be a responsible OpenWeather API user.

**Comment by sqfmi** [comment]
Good call, updated in 55cb672cee6fa4ed3f14f92e804609e45b722dd7
