### ISSUE TITLE
Not updating/ not getting out of deep sleep

### ISSUE THREAD

**Issue by Filipp1992** [sqfmi/Watchy#44]
I followed the instructions and managed to make the watchy run.
So far I couldn't manage to make it update or show the right time. 
It looks like the real time clock is not working properly?
When I upload the code the following warning comes up:
_WARNING: library DS3232RTC-1.3.0 claims to run on avr architecture(s) and may be incompatible with your current board which runs on esp32 architecture(s)._ 
But it still uploads the code. Might this be the problem? 
Then It shows the watch face but sticks to the shown time. And doesn't change at all. 
I reinstalled all the libraries, but didn't helped.

**Comment by mipek** [comment]
I think this is related to #40

**Comment by Filipp1992** [comment]
Thanks, yes that issues looks like the same. I missed it..
