### ISSUE TITLE
Issue with the display on watchy

### ISSUE THREAD

**Issue by nini1294** [sqfmi/Watchy#46]
Hi,

I just received my watchy and was assembling it. I saw that the display looked off and the top half is not updating and just the bottom half is updating. I tried to disconnect and reconnect the display, but that is not working.

![image](https://user-images.githubusercontent.com/6395125/121791761-48b69d80-cba2-11eb-9258-36fee819082b.png)

Thanks,
Nishant

**Comment by sqfmi** [comment]
Hi @nini1294 , it looks like you might have cracked the display during assembly. The original image from factory testing is still being shown on top, whereas the image update after assembly is happening in the bottom half of the display.

**Comment by nini1294** [comment]
Hi, is there anything I can do about it? Can I get a replacement. I dont know when it might have cracked.

**Comment by sqfmi** [comment]
Yes we offer replacement screens for $10 (free shipping for US) and includes the double sided tape. If you think the screen may have been damaged during shipping then you may want to go through UPS and claim for damages. If you would like to order a replacement you can fill out this form: https://forms.gle/hS3K4UnD1mdQbwnb8
