### ISSUE TITLE
Out of stock? 

### ISSUE THREAD

**Issue by elfranne** [sqfmi/Watchy#5]
The PayPal link say out of stock. Will it be back soon?

**Comment by sqfmi** [comment]
Yes :)

**Comment by cboddy** [comment]
+1

**Comment by cboddy** [comment]
Could you announce when there is more stock in this thread, please? Super keen to make an order.

**Comment by cr0mbly** [comment]
> Could you announce when there is more stock in this thread, please? Super keen to make an order.

Same here, making a note for later :)

**Comment by ymorayko** [comment]
Same here, waiting for it to become available.

**Comment by dansmyth** [comment]
Ditto. Itching for this thing.
You did a great job.

**Comment by biasedlogic** [comment]
Note #6 before you order. This repository didn't update code in past 2 months, it's all 'hello world' level code.

**Comment by sqfmi** [comment]
Please visit https://watchy.sqfmi.com for full documentation, it's also back on sale here https://www.tindie.com/products/sqfmi/watchy/

Thanks!
