### ISSUE TITLE
Time is 2 minutes off after one day

### ISSUE THREAD

**Issue by etwasmitbaum** [sqfmi/Watchy#54]
Hello, I set my Watchy time manually in the settings about 20 hours ago. Now I noticed that the time is about 2 minutes too early. Here is a picture of it:
My PC clock is synced, and I set the Watchy time with my PC. 
EDIT: I am using Firmware version 1.2.6
![](https://user-images.githubusercontent.com/47484288/122061862-32e9e800-cdef-11eb-9d2b-41fb00d7b15f.png)

**Comment by adamm** [comment]
Personally, I haven't seen this with the RTC, but I purposely set my watch time about a minute ahead of realtime.  It's remained roughly in sync all weekend.

I think there are three things are needed to solve your issue.

1. The ESP sleep timer needs to not default to 60000000us, and instead calculate the microseconds until the next zero-second minute, less the time it takes to wake up and actually refresh the display.
2. If Wifi is set, default to an NTP server that refreshes itself once a day.
3. The user will still need to set their timezone.  The "Set Time" menu option can be used for that.

Personally, I was able to implement 1 and 2 on my https://github.com/adamm/esp8266-clockradio project.  Should be trivial to port it over to here.

I can try to port the concept over to this project this weekend and submit a PR.

**Comment by etwasmitbaum** [comment]
The ESP sleep timer by default is handled with the DS3231 which is probably broken in my watch. 
If you add `#define ESP_RTC 1` in the `config.h` file it will use the RTC of the ESP32 which is very unprecise. But you are right, you can set the sleep timer to a calculated value so its exactly one minute.
Also I actually tried myself to implement an NTP server connection, but I am still struggling with battery issues while using it.

Would be great if you can implement 1. and 2. and create a PR. Probably your solution would be better than mine is.

**Comment by OverThinker** [comment]
> The ESP sleep timer by default is handled with the DS3231 which is probably broken in my watch.
> If you add `#define ESP_RTC 1` in the `config.h` file it will use the RTC of the ESP32 which is very unprecise. But you are right, you can set the sleep timer to a calculated value so its exactly one minute.
> Also I actually tried myself to implement an NTP server connection, but I am still struggling with battery issues while using it.
> 
> Would be great if you can implement 1. and 2. and create a PR. Probably your solution would be better than mine is.

If you look in the developer discord channel, I (AaronB) posted my ntp code.  It is working well for me so far updating the clock three times a day.

**Comment by etwasmitbaum** [comment]
@OverThinker I found your code on Discord and it looks great. I tried to implement it but I am getting an error `struct tm timeinfo;`.
The error is: 
```
src/Watchy_7_SEG.cpp: In member function 'void Watchy7SEG::syncNtpTime()':
src/Watchy_7_SEG.cpp:33:15: error: aggregate 'tm timeinfo' has incomplete type and cannot be defined
     struct tm timeinfo;
               ^
```
Any idea what I am doing wrong?

**Comment by etwasmitbaum** [comment]
@OverThinker Your code is working great! Thanks!

**Comment by schodet** [comment]
@etwasmitbaum can you open a pull request?

**Comment by schodet** [comment]
Also, this is a workaround but the RTC is not supposed to have a drift like this, 2 minutes a day is an error of 1388 ppm, while the DS3231M is supposed to have an accuracy of 2 ppm. There is something wrong with the RTC.

**Comment by etwasmitbaum** [comment]
> @etwasmitbaum can you open a pull request?

I just did! This was my first time ever doing a pull request.

>Also, this is a workaround but the RTC is not supposed to have a drift like this, 2 minutes a day is an error of 1388 ppm, while the DS3231M is supposed to have an accuracy of 5 ppm. There is something wrong with the RTC.

Thanks for the info. I contacted SQFMI about it.
