### ISSUE TITLE
Instructions for update via bluetooth

### ISSUE THREAD

**Issue by derak-kilgo** [sqfmi/Watchy#55]
Sorry if this is a dumb question. I'm new to hackable hardware.

I can put watchy in to firmware update mode and connect it to a device, but I'm not sure what to do after that.
Being connected doesn't add any ports in the arduinio ide and the mode isn't mentioned in the documentation.
Can compiled sketches be upload to watchy via bluetooth?

**Comment by sqfmi** [comment]
@derak-kilgo the compiled sketches are uploaded via USB though the Arduino. For BLE, currently we only support uploading our pre-compiled watchfaces by clicking on "Try It! (beta)" at https://watchy.sqfmi.com/watchfaces . You should use a browser that supports Web BLE e.g. Chrome

**Comment by notmatt** [comment]
@sqfmi Thanks! I tried basically everything except watch faces on the site ("why would firmware be there? 🤣 ")

**Comment by sqfmi** [comment]
Closing this issue, will fix bug in https://github.com/sqfmi/Watchy/issues/65

**Comment by escopecz** [comment]
There is no "Try it" button there anymore, right? Or am I blind?
