### ISSUE TITLE
Use ALARM1 for second updates?

### ISSUE THREAD

**Issue by sthornington** [sqfmi/Watchy#58]
Is this possible? It seems possible at first blush and kinda working but I think it might break the button interrupts?

**Comment by jeandeaual** [comment]
[This watchface](https://git.sr.ht/~jochen/Calculateur/tree/master/item/Calculateur.cpp) is using ALARM1, but it seems to be reimplementing most of the Watchy library.

**Comment by sqfmi** [comment]
You can use both ALARM1 and ALARM2, second updates however will greatly decrease battery life. Keep in mind it takes a few hundred ms for ESP32 to wake from deepsleep and refreshing the screen.
