### ISSUE TITLE
ESP32 stops responding after WLAN connection

### ISSUE THREAD

**Issue by rainer38** [sqfmi/Watchy#64]
Hi,

i modified the "DOS" WatchFace a little bit and at first everything went fine. Now i want the ESP32 to connect to my WLAN and do something over the network which works as expected. At the end of all the ESP32 gets back to deep sleep and it stops responding to the buttons or the RTC interrupt.
As soon as i call the function connectWiFi() the ESP32 doesn't get up anymore when going into deep sleep mode. But while it is awake everything works as expected, even the network transmissions do work.

I added some serial debugging lines to Watchy.cpp:

    void Watchy::init(String datetime){
        esp_sleep_wakeup_cause_t wakeup_reason;
        wakeup_reason = esp_sleep_get_wakeup_cause(); //get wake up reason
        Wire.begin(SDA, SCL); //init i2c
        Serial.begin(115200);
        Serial.print("Wakeup: ");

        switch (wakeup_reason)
        {
            #ifdef ESP_RTC
            case ESP_SLEEP_WAKEUP_TIMER: //ESP Internal RTC
                Serial.println("RTC intern");
                if(guiState == WATCHFACE_STATE){
                    RTC.read(currentTime);
                    currentTime.Minute++;
                    tmElements_t tm;
                    tm.Month = currentTime.Month;
                    tm.Day = currentTime.Day;
                    tm.Year = currentTime.Year;
                    tm.Hour = currentTime.Hour;
                    tm.Minute = currentTime.Minute;
                    tm.Second = 0;
                    time_t t = makeTime(tm);
                    RTC.set(t);
                    RTC.read(currentTime);           
                    showWatchFace(true); //partial updates on tick
                }
                break;        
            #endif
            case ESP_SLEEP_WAKEUP_EXT0: //RTC Alarm
                Serial.println("RTC extern");
                RTC.alarm(ALARM_2); //resets the alarm flag in the RTC
                if(guiState == WATCHFACE_STATE){
                    RTC.read(currentTime);
                    showWatchFace(true); //partial updates on tick
                }
                break;
            case ESP_SLEEP_WAKEUP_EXT1: //button Press
                Serial.println("Button");
                handleButtonPress();
                break;
            default: //reset
                Serial.println("Reset");
                #ifndef ESP_RTC
                _rtcConfig(datetime);
                #endif
                _bmaConfig();
                showWatchFace(false); //full update on reset
                break;
        }
        Serial.println("Power down");
        deepSleep();
    }

Here is the relevant part which i added to the Watchy_DOS.cpp file:

    void WatchyDOS::drawWatchFace() {
        Serial.println("Start Watchface");
    ...
        networkActions();
        Serial.println("End Watchface");
    }

    void WatchyDOS::networkActions() {
        Serial.print("WLAN: ");
        if (connectWiFi()) {
            Serial.println("OK");
            Serial.print("SSID:");
            Serial.println(WiFi.SSID());
            Serial.print("IP:");
            Serial.println(WiFi.localIP().toString());

            // do domething
    //      transmitData();

            Serial.println("Stop Wlan");
            WiFi.mode(WIFI_OFF);
        }
        else
            Serial.println("ERR");
    }

I can see in the serial console that the ESP32 starts up fine, connects to my WLAN and shows the assigned IP and at the end goes back to to deep sleep.
But after that nothing happens anymore, no response to the buttons nor wakeup from RTC. If i comment out the function networkActions() everything works as expected and it wakes up by button press or RTC interrupt.

So is there something i'm missing for the WLAN connection to used?

**Comment by sqfmi** [comment]
Please update to the latest library and re-open if issue persists.
