### ISSUE TITLE
Watchy's RTC is slow

### ISSUE THREAD

**Issue by slugh23** [sqfmi/Watchy#74]
According to the data sheet for the DS3231MZ, the accuracy of the RTC should be:

> Timekeeping Accuracy ±5ppm (±0.432 Second/Day)
> from -45°C to +85°C

I received my watchy three days ago (Wednesday) and set the time to within ±1 minute.  Watchy has been sitting on my desk since it arrived.  Within a day it lost 1-2 minutes.  I reset the time to ±1 minute.  Today--two days after the last adjustment--watchy is now 3-4 minutes slow.

**Comment by putz612** [comment]
Same issue for me, received it this week and have lost a few minutes every day.

**Comment by vanEgmond** [comment]
Probably related: #40

**Comment by slugh23** [comment]
Seems to be.  Mine is marked 1611A3 597AD.  Now just wondering what the remedy is.

**Comment by vanEgmond** [comment]
Contact sqfmi on Discord or write them an email, they are currently figuring out logistics as it seems like a bad batch.
1611A3 597AD is one of the serials that keeps popping up.

**Comment by slugh23** [comment]
Thank you very much!
