### ISSUE TITLE
Link to discord server on homepage expired

### ISSUE THREAD

**Issue by lightnin** [sqfmi/Watchy#81]
The link to the discord server on the FAQ page here:
https://watchy.sqfmi.com/docs/faqs

Is expired, and results in this  error:

<img width="557" alt="Screenshot 2021-07-30 at 12 22 43" src="https://user-images.githubusercontent.com/1538027/127640232-38f4e8c3-cbe8-43b4-b5ca-30bc41d1e005.png">

It seems like you could use some better support channels, before the returns start flowing back.

**Comment by lightnin** [comment]
Note that searching for "SQFMI discord server" doesn't yield any useful results, so AFAIK the only way to get support is to file an issue on github.

**Comment by sqfmi** [comment]
You can try to Discord link on our homepage https://discord.gg/ZXDegGV8E7 , that link appears to have expired and needs to be updated
