### ISSUE TITLE
Menu button doesn't work if watch is woken with any button other than menu button

### ISSUE THREAD

**Issue by clayton-rogers** [sqfmi/Watchy#84]
Steps to reproduce:
- Be on the watch face
- Press any button except for menu button
- Press the menu button

Expect menu should be entered but nothing happens.

When "experimental fast menu" was implemented, the menu button handling code wasn't copied directly. So if you get into the fast menu handling code and you're on the watch face, then the menu button does nothing. You have to wait for the watch to sleep, then press the menu button.

Is there any benefit to `showFastMenu()` over just doing a partial refresh? It seems identical other than omitting the call to `init()`.

Given the signification code duplication to implement fast menu, I'm inclined to mostly remove it but merge the keep-awake behaviour with the existing button handling code.

**Comment by sqfmi** [comment]
Fixed in recent releases. Please re-open if issue persists.
