### ISSUE TITLE
Watch Face Doesn't Change After Successful Sketch Upload

### ISSUE THREAD

**Issue by tex792** [sqfmi/Watchy#88]
The watch face does not change from the default screen that it ships with. When I upload a sketch, it seems to upload successfully and ends with "Done uploading." in the Arduino IDE.

Could a crack on the back of the screen possibly affect the entire display? When I very first opened the package, the screen slipped out and landed on the floor. It has a visible crack on the back, but the front looks ok.

Update: I also tried to load a simple sketch to blink the onboard LED. I believe this is connected to pin 2 on the ESP32, but that did not seem to work. I switched it to the usual Arduino pin (pin 13), it would turn the onboard vibration motor on and off.

**Comment by sqfmi** [comment]
A crack would probably affect the screen from refreshing, also make sure the ribbon cable is properly connected. You can purchase a replacement screen here https://www.aliexpress.com/item/33044560386.html. The LED indicates charge status and is not connected to any GPIOs.

**Comment by tex792** [comment]
Thank you! I checked in the Discord chat as well and folks seemed to think the same thing. I went ahead and ordered a few of the replacement screens from AliExpress. Also that's good to know regarding the onboard LED; I wasn't aware of that.
