### ISSUE TITLE
"set time" menu option doesn't work well

### ISSUE THREAD

**Issue by GregDMeyer** [sqfmi/Watchy#92]
When I try to use the "set time" menu option, upon first entering it is very "noisy"---lots of dots everywhere (this is the only option where this happens). As it flashes the numbers in the time, it gets a little bit better until eventually it looks ok. 

I also find that the buttons aren't very responsive in this menu specifically---it only responds to maybe every 5th button press. Maybe also has to do with the flashing?

**Comment by seasick** [comment]
I have made the experience that it is working better if I keep the button down and wait for the right number to appear, and then let the button go
